name:                GroupUp
version:             0.1.0.0
github:              "drom3/GroupUp"
license:             BSD3
author:              "Daniel Romero"
maintainer:          "drom3@users.noreply.github.com"
copyright:           "2019 Daniel Romero"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/drom3/GroupUp#readme>

dependencies:
- base >= 4.7 && < 5

data-files: firstnames.txt
data-dir: data

library:
  source-dirs: src

executables:
  GroupUp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GroupUp

tests:
  GroupUp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GroupUp
